name: 'SOOS DAST'
author: 'SOOS'
description: 'The SOOS GitHub Action to perform the DAST Analysis.'
branding:
  icon: 'alert-triangle'
  color: 'blue'
inputs:
  client_id:
    description: 'SOOS Client Id.'
    required: true
  api_key:
    description: 'SOOS API Key.'
    required: true
  project_name:
    description: 'The project name that will be displayed on the dashboard. By Default is owner/repository_name.'
    required: true
    default: ${{ github.repository }}
  scan_mode:
    description: 'SOOS DAST scan mode. Values available: baseline (Default), fullscan, and apiscan.'
    required: true
    default: 'baseline'
  on_failure:
    description: 'Action to perform when the scan fails. Values available: fail_the_build, continue_on_failure (Default)'
    required: false
    default: 'continue_on_failure'
  api_url:
    description: 'SOOS API URL.'
    required: true
    default: 'https://api.soos.io/api/'
  target_url:
    description: 'Target URL to perform the scan against.'
    required: true
  debug:
    description: 'Show debug messages.'
    required: false
    default: 'false'
  ajax_spider:
    description: 'Enable the Ajax spider in addition to the traditional one.'
    required: false
    default: 'false'
  context_file:
    description: 'Context file which will be loaded prior to scanning the target.'
    required: false
  disable_rules:
    description: 'Comma separated list of ZAP rules IDs to disable. List for reference https://www.zaproxy.org/docs/alerts/. (e.g. 10001,10002)'
    required: false
  full_scan_minutes:
    description: 'The number of minutes for spider to run (required if scanmode is fullScan).'
    required: false
  api_scan_format:
    description: 'Target API format: openapi, soap, or graphql. Required for scan_mode: apiscan.'
    required: false
  log_level:
    description: 'Log level to show: DEBUG, INFO, WARN, ERROR, CRITICAL.'
    required: false
    default: 'INFO'
  branch_uri:
    description: 'URI to branch from SCM system.'
    required: false
    default: ''
  branch_name:
    description: 'Branch Name to create scan under'
    required: false
    default: ''
  build_version:
    description: 'Version of application build artifacts.'
    required: false
    default: ''
  build_uri:
    description: 'URI to CI build info.'
    required: false
    default: ''
  operating_environment:
    description: 'System info regarding operating system, etc.'
    required: false
    default: ${{ runner.os }}
  output_format:
    description: 'Output format for report to be generated (only sarif supported at the moment).'
    required: false
    default: ''
  zap_options:
    description: 'ZAP Additional Options.'
    required: false
  request_cookies:
    description: 'Set Cookie values for the requests to the target URL.'
    required: false
  request_headers:
    description: 'Set extra header requests.'
    required: false
  bearer_token:
    description: 'Bearer token to include as authorization header in every request.'
    required: false
  auth_username:
    description: 'Username to use in auth apps.'
    required: false
  auth_password:
    description: 'Password to use in auth apps.'
    required: false
  auth_login_url:
    description: 'Login url to use in auth apps.'
    required: false
  auth_username_field:
    description: 'Username input id to use in auth apps.'
    required: false
  auth_password_field:
    description: 'Password input id to use in auth apps.'
    required: false
  auth_submit_field:
    description: 'Submit button id to use in auth apps.'
    required: false
  auth_second_submit_field:
    description: 'Second submit button id to use in auth apps (for multi-page forms).'
    required: false
  auth_form_type:
    description: 'simple (all fields are displayed at once), wait_for_password (Password field is displayed only after username is filled), or multi_page (Password field is displayed only after username is filled and submit is clicked)'
    required: false
  auth_delay_time:
    description: 'Delay time in seconds to wait for the page to load after performing actions in the form. (Used only on authFormType: wait_for_password and multi_page)'
    required: false
  auth_submit_action:
    description: 'Submit action to perform on form filled. Possible values are click or submit.'
    required: false
  oauth_token_url:
    description: 'The fully qualified authentication URL that grants the access_token.'
    required: false
  oauth_parameters:
    description: 'Parameters to be added to the oauth token request. (eg: client_id:value, client_secret:value, grant_type:value).'
    required: false
  auth_verification_url:
    description: 'URL used to verify authentication success. If authentication fails when this URL is provided, the scan will be terminated.'
    required: false
  verbose:
    description: 'Enable verbose logging.'
    required: false
  other_options:
    description: 'Other command line arguments sent directly to the script for items not supported by other command line arguments'
    required: false
runs:
  using: 'docker'
  image: docker://soosio/dast-github:beta
  env:
    SOOS_AJAX_SPIDER: ${{ inputs.ajax_spider }}
    SOOS_API_KEY: ${{ inputs.api_key }}
    SOOS_API_SCAN_FORMAT: ${{ inputs.api_scan_format }}
    SOOS_API_URL: ${{ inputs.api_url }}
    SOOS_AUTH_DELAY_TIME: ${{ inputs.auth_delay_time }}
    SOOS_AUTH_FORM_TYPE: ${{ inputs.auth_form_type }}
    SOOS_AUTH_LOGIN_URL: ${{ inputs.auth_login_url }}
    SOOS_AUTH_PASSWORD: ${{ inputs.auth_password }}
    SOOS_AUTH_PASSWORD_FIELD: ${{ inputs.auth_password_field }}
    SOOS_AUTH_SECOND_SUBMIT_FIELD: ${{ inputs.auth_second_submit_field }}
    SOOS_AUTH_SUBMIT_ACTION: ${{ inputs.auth_submit_action }}
    SOOS_AUTH_SUBMIT_FIELD: ${{ inputs.auth_submit_field }}
    SOOS_AUTH_USERNAME: ${{ inputs.auth_username }}
    SOOS_AUTH_USERNAME_FIELD: ${{ inputs.auth_username_field }}
    SOOS_AUTH_VERIFICATION_URL: ${{ inputs.auth_verification_url }}
    SOOS_BEARER_TOKEN: ${{ inputs.bearer_token }}
    SOOS_BRANCH_NAME: ${{ inputs.branch_name }}
    SOOS_BRANCH_URI: ${{ inputs.branch_uri }}
    SOOS_BUILD_URI: ${{ inputs.build_uri }}
    SOOS_BUILD_VERSION: ${{ inputs.build_version }}
    SOOS_CLIENT_ID: ${{ inputs.client_id }}
    SOOS_CONTEXT_FILE: ${{ inputs.context_file }}
    SOOS_CONTEXT_USER: ${{ inputs.context_user }}
    SOOS_DEBUG: ${{ inputs.debug }}
    SOOS_DISABLE_RULES: ${{ inputs.disable_rules }}
    SOOS_FULL_SCAN_MINUTES: ${{ inputs.full_scan_minutes }}
    SOOS_LOG_LEVEL: ${{ inputs.log_level }}
    SOOS_OAUTH_PARAMETERS: ${{ inputs.oauth_parameters }}
    SOOS_OAUTH_TOKEN_URL: ${{ inputs.oauth_token_url }}
    SOOS_ON_FAILURE: ${{ inputs.on_failure }}
    SOOS_OPERATING_ENVIRONMENT: ${{ inputs.operating_environment }}
    SOOS_OTHER_OPTIONS: ${{ inputs.other_options }}
    SOOS_OUTPUT_FORMAT: ${{ inputs.output_format }}
    SOOS_PROJECT_NAME: ${{ inputs.project_name }}
    SOOS_REQUEST_COOKIES: ${{ inputs.request_cookies }}
    SOOS_REQUEST_HEADERS: ${{ inputs.request_headers }}
    SOOS_SCAN_MODE: ${{ inputs.scan_mode }}
    SOOS_TARGET_URL: ${{ inputs.target_url }}
    SOOS_VERBOSE: ${{ inputs.verbose }}
    SOOS_ZAP_OPTIONS: ${{ inputs.zap_options }}
